on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '17'
        cache: 'gradle'
    - name: Lint
      run: ./gradlew detekt lint
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '17'
        cache: 'gradle'
    - name: Run tests
      run: ./gradlew testDebug --continue
  assemble:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: '17'
          cache: 'gradle'
      - name: Build APK
        run: ./gradlew assemble
